---
networks:
  frontend:
    external: true
  backend:
    external: true
volumes:
  influxdb-data:
services:
  influxdb:
    container_name: ixdb-prod-1
    image: influxdb:1.8.10
    volumes:
      - influxdb2-data:/var/lib/influxdb
      - ./etc:/etc/influxdb
    labels:
      - traefik.enable=true
      - traefik.http.services.ixdb-prod-1.loadbalancer.server.port=8086
      - traefik.http.services.ixdb-prod-1.loadbalancer.server.scheme=http
      - traefik.http.routers.ixdb-prod-1-https.entrypoints=websecure
      - traefik.http.routers.ixdb-prod-1-https.rule=Host(`ixdb-prod-1.srv-prod-2.local.prox-lab.de`)
      - traefik.http.routers.ixdb-prod-1-https.tls=true
      - traefik.http.routers.ixdb-prod-1-https.tls.certresolver=cloudflare
      - traefik.http.services.ixdb-gpht-prod-1.loadbalancer.server.port=2003
      - traefik.http.services.ixdb-gpht-prod-1.loadbalancer.server.scheme=http
      - traefik.http.routers.ixdb-gpht-prod-1-https.entrypoints=websecure
      - traefik.http.routers.ixdb-gpht-prod-1-https.rule=Host(`ixdb-gpht-prod-1.srv-prod-2.local.prox-lab.de`)
      - traefik.http.routers.ixdb-gpht-prod-1-https.tls=true
      - traefik.http.routers.ixdb-gpht-prod-1-https.tls.certresolver=cloudflare
    networks:
      - frontend
      - backend
    restart: unless-stopped