name: "Update DNS Records"

on:
  push:
    branches:
      - main
    paths:
      - 'dns/dns-prod-1/terraform/*.tf'
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - 'dns/dns-prod-1/terraform/*.tf'
  workflow_dispatch:
  
defaults:
  run:
    working-directory: dns/dns-prod-1/terraform

env:
  TF_VAR_TSIG_KEY_HOME: ${{ secrets.TSIG_KEY_HOME }}

jobs:
  terraform:
    runs-on: "self-hosted"
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -out
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: steps.plan.outcome == 'success'
        run: terraform apply -auto-approve -input=false